spring:  mail:    host: smtp.gmail.com
    port: 587
    username: thedillip1@gmail.com
    password: ierosibqhhohxdaq
    name: Dillip K Sahoo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true